version: '3'
services:
  mosquitto:
    build:
      context: ./mqtt
      dockerfile: Dockerfile.mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
  go-server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      MQTT_BROKER: mosquitto