FROM golang:1.21.1 as builder

# Enable go modules
ENV GO111MODULE=on

WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# switch to smaller final image to run binary
FROM alpine:latest

COPY --from=builder /build/main /app/

WORKDIR /app

# Run the binary
CMD ["./main"]
